### ISSUE TITLE
Rename randomlmao() in frontend/src/ServerDetails

### ISSUE THREAD

**Issue by ryzbaka** [ryzbaka/PyLot#7]
It would be better if the randomlmao() is renamed to removeserver or something like that. Please use camel case.

**Comment by MSTEWARDSON** [comment]
Can I be assigned this issue?

**Comment by ryzbaka** [comment]
You have been assigned this issue.

**Comment by MSTEWARDSON** [comment]
I have created a pull request to fix this issue. 

[0bfc033](https://github.com/ryzbaka/PyLot/pull/10)

**Comment by ryzbaka** [comment]
[Solved](https://github.com/ryzbaka/PyLot/pull/10).
