### ISSUE TITLE
Integrate express router functionality in backend

### ISSUE THREAD

**Issue by ryzbaka** [ryzbaka/PyLot#8]
Split up the various routes in backend/src/node.js into separate files using express router.

**Comment by ryzbaka** [comment]
[This](https://xpertphp.com/node-js-routes-in-separate-file-using-express/) can help.

**Comment by Bhavesh27** [comment]
@ryzbaka Can you assign me this. I can take this up.

**Comment by Bhavesh27** [comment]
@ryzbaka https://github.com/ryzbaka/PyLot/pull/11 Created a UserController for /users api

**Comment by guptapranav4299** [comment]
I can also contribute to this issue @ryzbaka

**Comment by ryzbaka** [comment]
@guptapranav4299 @Bhavesh27 , both have been assigned this issue. You can choose to collaborate or work individually. I'll merge the PR that fixes the issue.

**Comment by Bhavesh27** [comment]
@ryzbaka PR: - https://github.com/ryzbaka/PyLot/pull/11 For review
