### ISSUE TITLE
Update documentation for node.js backend

### ISSUE THREAD

**Issue by ryzbaka** [ryzbaka/PyLot#9]
The documentation for the pylot.codes backend is not up to date with the server.js application in the backend/src folder.
Update the documentation to match the server.js file.

**Comment by ryzbaka** [comment]
Documentation can be found in the `gh-pages` branch of the repository and involves updating the included markdown files, Jenkins handles the rest.

**Comment by nk183** [comment]
@ryzbaka ,can I work on this issue?

**Comment by ryzbaka** [comment]
Sure thing @nk183 , just create a pull request with the changes.

**Comment by nk183** [comment]
@ryzbaka ,where can I edit Documentation
I am not able edit in  Documentation ([https://ryzbaka.github.io/PyLot/]) directly

**Comment by nk183** [comment]
[d](https://ryzbaka.github.io/PyLot/)

**Comment by nk183** [comment]
@ryzbaka  please guide where I can edit Documentation

**Comment by ryzbaka** [comment]
@nk183 if you clone the repo and move to the gh-pages repo, you'll find an index.md file which can be edited.

**Comment by nk183** [comment]
Hi @ryzbaka  have made a pull request please check - #13
